---
- project:
    name: PROJECT
    project: PROJECT
    project-name: 'PROJECT'

    project-pattern: 'PROJECT'
    rtd-build-url: RTD_BUILD_URL
    rtd-token: RTD_TOKEN

    jobs:
      - '{project-name}-rtd-jobs'
